// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ari.proto

package ari

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	types "github.com/gogo/protobuf/types"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Key identifies a unique resource in the system
type Key struct {
	// Kind indicates the type of resource the Key points to.  e.g., "channel",
	// "bridge", etc.
	Kind string `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	// ID indicates the unique identifier of the resource
	ID string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Node indicates the unique identifier of the Asterisk node on which the
	// resource exists or will be created
	Node string `protobuf:"bytes,3,opt,name=node,proto3" json:"node,omitempty"`
	// Dialog indicates a named scope of the resource, for receiving events
	Dialog string `protobuf:"bytes,4,opt,name=dialog,proto3" json:"dialog,omitempty"`
	// App indiciates the ARI application that this key is bound to.
	App                  string   `protobuf:"bytes,5,opt,name=app,proto3" json:"app,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Key) Reset()      { *m = Key{} }
func (*Key) ProtoMessage() {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_01b1a3f980fd6d07, []int{0}
}
func (m *Key) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Key.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return m.Size()
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Key) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Key) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *Key) GetDialog() string {
	if m != nil {
		return m.Dialog
	}
	return ""
}

func (m *Key) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

// CallerID describes the name and number which identifies the caller to other endpoints
type CallerID struct {
	// Name is the name of the party
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Number is the number of the party
	Number               string   `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CallerID) Reset()      { *m = CallerID{} }
func (*CallerID) ProtoMessage() {}
func (*CallerID) Descriptor() ([]byte, []int) {
	return fileDescriptor_01b1a3f980fd6d07, []int{1}
}
func (m *CallerID) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CallerID) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CallerID.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CallerID) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CallerID.Merge(m, src)
}
func (m *CallerID) XXX_Size() int {
	return m.Size()
}
func (m *CallerID) XXX_DiscardUnknown() {
	xxx_messageInfo_CallerID.DiscardUnknown(m)
}

var xxx_messageInfo_CallerID proto.InternalMessageInfo

func (m *CallerID) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CallerID) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

// ChannelData describes the data for a specific channel
type ChannelData struct {
	// Key is the key of the channel
	Key *Key `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Id is the unique ID for this channel (AMI-style)
	ID string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// Name is the name of this channel (tect/name-id)
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// State is the current state of the channel
	State string `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	// Accountcode is the account code assigned to the channel
	Accountcode string `protobuf:"bytes,5,opt,name=accountcode,proto3" json:"accountcode,omitempty"`
	// Caller is the callerID of the calling endpoint
	Caller *CallerID `protobuf:"bytes,6,opt,name=caller,proto3" json:"caller,omitempty"`
	// Connected is the callerID of the connected line, if applicable
	Connected *CallerID `protobuf:"bytes,7,opt,name=connected,proto3" json:"connected,omitempty"`
	// Creationtime is the time at which the channel was created
	Creationtime *types.Timestamp `protobuf:"bytes,8,opt,name=creationtime,proto3" json:"creationtime,omitempty"`
	// Dialplan is the current location of the channel in the dialplan
	Dialplan *DialplanCEP `protobuf:"bytes,9,opt,name=dialplan,proto3" json:"dialplan,omitempty"`
	// Language is the default spoken language for this channel
	Language string `protobuf:"bytes,10,opt,name=language,proto3" json:"language,omitempty"`
	// ChannelVars is the list of channel variables set on this channel
	ChannelVars          map[string]string `protobuf:"bytes,11,rep,name=channelvars,proto3" json:"channelvars,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ChannelData) Reset()         { *m = ChannelData{} }
func (m *ChannelData) String() string { return proto.CompactTextString(m) }
func (*ChannelData) ProtoMessage()    {}
func (*ChannelData) Descriptor() ([]byte, []int) {
	return fileDescriptor_01b1a3f980fd6d07, []int{2}
}
func (m *ChannelData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ChannelData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ChannelData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ChannelData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChannelData.Merge(m, src)
}
func (m *ChannelData) XXX_Size() int {
	return m.Size()
}
func (m *ChannelData) XXX_DiscardUnknown() {
	xxx_messageInfo_ChannelData.DiscardUnknown(m)
}

var xxx_messageInfo_ChannelData proto.InternalMessageInfo

func (m *ChannelData) GetKey() *Key {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ChannelData) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ChannelData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ChannelData) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *ChannelData) GetAccountcode() string {
	if m != nil {
		return m.Accountcode
	}
	return ""
}

func (m *ChannelData) GetCaller() *CallerID {
	if m != nil {
		return m.Caller
	}
	return nil
}

func (m *ChannelData) GetConnected() *CallerID {
	if m != nil {
		return m.Connected
	}
	return nil
}

func (m *ChannelData) GetCreationtime() *types.Timestamp {
	if m != nil {
		return m.Creationtime
	}
	return nil
}

func (m *ChannelData) GetDialplan() *DialplanCEP {
	if m != nil {
		return m.Dialplan
	}
	return nil
}

func (m *ChannelData) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *ChannelData) GetChannelVars() map[string]string {
	if m != nil {
		return m.ChannelVars
	}
	return nil
}

// Dialplan describes a location in the Asterisk dialplan
type DialplanCEP struct {
	// Context describes the section in the dialplan
	Context string `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	// Exten describes the label in the section of the dialplan
	Exten string `protobuf:"bytes,2,opt,name=exten,proto3" json:"exten,omitempty"`
	// Priority indicates the index at the label in the section of the dialplan
	Priority             int64    `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DialplanCEP) Reset()         { *m = DialplanCEP{} }
func (m *DialplanCEP) String() string { return proto.CompactTextString(m) }
func (*DialplanCEP) ProtoMessage()    {}
func (*DialplanCEP) Descriptor() ([]byte, []int) {
	return fileDescriptor_01b1a3f980fd6d07, []int{3}
}
func (m *DialplanCEP) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DialplanCEP) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DialplanCEP.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DialplanCEP) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DialplanCEP.Merge(m, src)
}
func (m *DialplanCEP) XXX_Size() int {
	return m.Size()
}
func (m *DialplanCEP) XXX_DiscardUnknown() {
	xxx_messageInfo_DialplanCEP.DiscardUnknown(m)
}

var xxx_messageInfo_DialplanCEP proto.InternalMessageInfo

func (m *DialplanCEP) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *DialplanCEP) GetExten() string {
	if m != nil {
		return m.Exten
	}
	return ""
}

func (m *DialplanCEP) GetPriority() int64 {
	if m != nil {
		return m.Priority
	}
	return 0
}

func init() {
	proto.RegisterType((*Key)(nil), "asterisk.ari.Key")
	proto.RegisterType((*CallerID)(nil), "asterisk.ari.CallerID")
	proto.RegisterType((*ChannelData)(nil), "asterisk.ari.ChannelData")
	proto.RegisterMapType((map[string]string)(nil), "asterisk.ari.ChannelData.ChannelvarsEntry")
	proto.RegisterType((*DialplanCEP)(nil), "asterisk.ari.DialplanCEP")
}

func init() { proto.RegisterFile("ari.proto", fileDescriptor_01b1a3f980fd6d07) }

var fileDescriptor_01b1a3f980fd6d07 = []byte{
	// 526 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x52, 0xcd, 0x6a, 0xdb, 0x40,
	0x10, 0xae, 0x2c, 0xdb, 0xb1, 0x47, 0x81, 0x26, 0x4b, 0x30, 0x5b, 0x1f, 0x6c, 0xe3, 0x5e, 0x42,
	0xa1, 0x0a, 0xa4, 0x2d, 0x94, 0x50, 0x72, 0xb0, 0x9d, 0x43, 0xc8, 0xa5, 0x88, 0x52, 0x68, 0xa1,
	0x87, 0xb1, 0xb4, 0x55, 0x16, 0xcb, 0xbb, 0x62, 0xb5, 0x0a, 0xf1, 0x9b, 0xf4, 0xd8, 0x27, 0xe8,
	0x73, 0xf4, 0xd8, 0x27, 0x08, 0xc5, 0x4f, 0x12, 0x76, 0x57, 0xf2, 0x4f, 0x0e, 0xb9, 0xcd, 0x37,
	0xfa, 0xbe, 0x99, 0xfd, 0xf4, 0x0d, 0x74, 0x51, 0xf1, 0x30, 0x57, 0x52, 0x4b, 0x72, 0x88, 0x85,
	0x66, 0x8a, 0x17, 0x8b, 0x10, 0x15, 0xef, 0xbf, 0x4d, 0xb9, 0xbe, 0x2d, 0xe7, 0x61, 0x2c, 0x97,
	0x67, 0xa9, 0x4c, 0xe5, 0x99, 0x25, 0xcd, 0xcb, 0x9f, 0x16, 0x59, 0x60, 0x2b, 0x27, 0xee, 0x0f,
	0x53, 0x29, 0xd3, 0x8c, 0x6d, 0x59, 0x9a, 0x2f, 0x59, 0xa1, 0x71, 0x99, 0x3b, 0xc2, 0xb8, 0x04,
	0xff, 0x86, 0xad, 0x08, 0x81, 0xe6, 0x82, 0x8b, 0x84, 0x7a, 0x23, 0xef, 0xb4, 0x1b, 0xd9, 0x9a,
	0xf4, 0xa0, 0xc1, 0x13, 0xda, 0x30, 0x9d, 0x49, 0x7b, 0xfd, 0x30, 0x6c, 0x5c, 0xcf, 0xa2, 0x06,
	0x4f, 0x0c, 0x57, 0xc8, 0x84, 0x51, 0xdf, 0x71, 0x4d, 0x4d, 0x7a, 0xd0, 0x4e, 0x38, 0x66, 0x32,
	0xa5, 0x4d, 0xdb, 0xad, 0x10, 0x39, 0x02, 0x1f, 0xf3, 0x9c, 0xb6, 0x6c, 0xd3, 0x94, 0x17, 0xcd,
	0x5f, 0xbf, 0x87, 0x2f, 0xc6, 0x9f, 0xa0, 0x33, 0xc5, 0x2c, 0x63, 0xea, 0x7a, 0x66, 0xe7, 0xe1,
	0x92, 0xd5, 0xbb, 0x4d, 0x6d, 0xe6, 0x89, 0x72, 0x39, 0x67, 0xca, 0xed, 0x8f, 0x2a, 0x54, 0xa9,
	0xff, 0x34, 0x21, 0x98, 0xde, 0xa2, 0x10, 0x2c, 0x9b, 0xa1, 0x46, 0xf2, 0x1a, 0xfc, 0x05, 0x5b,
	0xd9, 0x01, 0xc1, 0xf9, 0x71, 0xb8, 0xfb, 0xc3, 0xc2, 0x1b, 0xb6, 0x8a, 0xcc, 0xd7, 0x67, 0xed,
	0x98, 0xf5, 0xfe, 0xce, 0xfa, 0x13, 0x68, 0x15, 0x1a, 0x35, 0xab, 0xdc, 0x38, 0x40, 0x46, 0x10,
	0x60, 0x1c, 0xcb, 0x52, 0xe8, 0xd8, 0xf8, 0x77, 0xa6, 0x76, 0x5b, 0x24, 0x84, 0x76, 0x6c, 0x6d,
	0xd1, 0xb6, 0x7d, 0x4b, 0x6f, 0xff, 0x2d, 0xb5, 0xe5, 0xa8, 0x62, 0x91, 0xf7, 0xd0, 0x8d, 0xa5,
	0x10, 0x2c, 0xd6, 0x2c, 0xa1, 0x07, 0xcf, 0x4a, 0xb6, 0x44, 0x72, 0x09, 0x87, 0xb1, 0x62, 0xa8,
	0xb9, 0x14, 0x26, 0x4e, 0xda, 0xb1, 0xc2, 0x7e, 0xe8, 0xb2, 0x0e, 0xeb, 0xac, 0xc3, 0x2f, 0x75,
	0xd6, 0xd1, 0x1e, 0x9f, 0x7c, 0x80, 0x8e, 0x89, 0x27, 0xcf, 0x50, 0xd0, 0xae, 0xd5, 0xbe, 0xda,
	0x5f, 0x3a, 0xab, 0xbe, 0x4e, 0xaf, 0x3e, 0x47, 0x1b, 0x2a, 0xe9, 0x43, 0x27, 0x43, 0x91, 0x96,
	0x98, 0x32, 0x0a, 0xd6, 0xfb, 0x06, 0x93, 0x1f, 0x10, 0xc4, 0x2e, 0x90, 0x3b, 0x54, 0x05, 0x0d,
	0x46, 0xfe, 0x69, 0x70, 0xfe, 0xe6, 0x89, 0x95, 0x6d, 0x62, 0x75, 0x6d, 0xc8, 0x57, 0x42, 0xab,
	0xd5, 0xe4, 0xe5, 0xfa, 0x61, 0x58, 0x67, 0xfa, 0x15, 0x55, 0x11, 0xed, 0xce, 0xeb, 0x5f, 0xc2,
	0xd1, 0x53, 0x85, 0x39, 0xad, 0x3a, 0xf4, 0xae, 0x4b, 0xf8, 0x04, 0x5a, 0x77, 0x98, 0x95, 0xac,
	0xba, 0x19, 0x07, 0x2e, 0x1a, 0x1f, 0xbd, 0xf1, 0x37, 0x08, 0x76, 0x3c, 0x11, 0x0a, 0x07, 0xb1,
	0x14, 0x9a, 0xdd, 0xeb, 0x4a, 0x5e, 0x43, 0x33, 0x82, 0xdd, 0x6b, 0x26, 0xea, 0x11, 0x16, 0x18,
	0xe7, 0xb9, 0xe2, 0x52, 0x71, 0xbd, 0xb2, 0x67, 0xe2, 0x47, 0x1b, 0x3c, 0x39, 0xfe, 0xbb, 0x1e,
	0x78, 0xff, 0xd6, 0x03, 0xef, 0xff, 0x7a, 0xe0, 0x7d, 0xf7, 0x51, 0xf1, 0x79, 0xdb, 0x26, 0xf0,
	0xee, 0x31, 0x00, 0x00, 0xff, 0xff, 0x98, 0xd4, 0xd1, 0x20, 0xc5, 0x03, 0x00, 0x00,
}

func (m *Key) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Key) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Key) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.App) > 0 {
		i -= len(m.App)
		copy(dAtA[i:], m.App)
		i = encodeVarintAri(dAtA, i, uint64(len(m.App)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Dialog) > 0 {
		i -= len(m.Dialog)
		copy(dAtA[i:], m.Dialog)
		i = encodeVarintAri(dAtA, i, uint64(len(m.Dialog)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Node) > 0 {
		i -= len(m.Node)
		copy(dAtA[i:], m.Node)
		i = encodeVarintAri(dAtA, i, uint64(len(m.Node)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ID) > 0 {
		i -= len(m.ID)
		copy(dAtA[i:], m.ID)
		i = encodeVarintAri(dAtA, i, uint64(len(m.ID)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Kind) > 0 {
		i -= len(m.Kind)
		copy(dAtA[i:], m.Kind)
		i = encodeVarintAri(dAtA, i, uint64(len(m.Kind)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *CallerID) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CallerID) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CallerID) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.Number) > 0 {
		i -= len(m.Number)
		copy(dAtA[i:], m.Number)
		i = encodeVarintAri(dAtA, i, uint64(len(m.Number)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintAri(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ChannelData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ChannelData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ChannelData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.ChannelVars) > 0 {
		for k := range m.ChannelVars {
			v := m.ChannelVars[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintAri(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintAri(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintAri(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x5a
		}
	}
	if len(m.Language) > 0 {
		i -= len(m.Language)
		copy(dAtA[i:], m.Language)
		i = encodeVarintAri(dAtA, i, uint64(len(m.Language)))
		i--
		dAtA[i] = 0x52
	}
	if m.Dialplan != nil {
		{
			size, err := m.Dialplan.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAri(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x4a
	}
	if m.Creationtime != nil {
		{
			size, err := m.Creationtime.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAri(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x42
	}
	if m.Connected != nil {
		{
			size, err := m.Connected.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAri(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	if m.Caller != nil {
		{
			size, err := m.Caller.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAri(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if len(m.Accountcode) > 0 {
		i -= len(m.Accountcode)
		copy(dAtA[i:], m.Accountcode)
		i = encodeVarintAri(dAtA, i, uint64(len(m.Accountcode)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.State) > 0 {
		i -= len(m.State)
		copy(dAtA[i:], m.State)
		i = encodeVarintAri(dAtA, i, uint64(len(m.State)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = encodeVarintAri(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ID) > 0 {
		i -= len(m.ID)
		copy(dAtA[i:], m.ID)
		i = encodeVarintAri(dAtA, i, uint64(len(m.ID)))
		i--
		dAtA[i] = 0x12
	}
	if m.Key != nil {
		{
			size, err := m.Key.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAri(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DialplanCEP) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DialplanCEP) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DialplanCEP) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Priority != 0 {
		i = encodeVarintAri(dAtA, i, uint64(m.Priority))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Exten) > 0 {
		i -= len(m.Exten)
		copy(dAtA[i:], m.Exten)
		i = encodeVarintAri(dAtA, i, uint64(len(m.Exten)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Context) > 0 {
		i -= len(m.Context)
		copy(dAtA[i:], m.Context)
		i = encodeVarintAri(dAtA, i, uint64(len(m.Context)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintAri(dAtA []byte, offset int, v uint64) int {
	offset -= sovAri(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Key) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Kind)
	if l > 0 {
		n += 1 + l + sovAri(uint64(l))
	}
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovAri(uint64(l))
	}
	l = len(m.Node)
	if l > 0 {
		n += 1 + l + sovAri(uint64(l))
	}
	l = len(m.Dialog)
	if l > 0 {
		n += 1 + l + sovAri(uint64(l))
	}
	l = len(m.App)
	if l > 0 {
		n += 1 + l + sovAri(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *CallerID) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovAri(uint64(l))
	}
	l = len(m.Number)
	if l > 0 {
		n += 1 + l + sovAri(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *ChannelData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Key != nil {
		l = m.Key.Size()
		n += 1 + l + sovAri(uint64(l))
	}
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovAri(uint64(l))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovAri(uint64(l))
	}
	l = len(m.State)
	if l > 0 {
		n += 1 + l + sovAri(uint64(l))
	}
	l = len(m.Accountcode)
	if l > 0 {
		n += 1 + l + sovAri(uint64(l))
	}
	if m.Caller != nil {
		l = m.Caller.Size()
		n += 1 + l + sovAri(uint64(l))
	}
	if m.Connected != nil {
		l = m.Connected.Size()
		n += 1 + l + sovAri(uint64(l))
	}
	if m.Creationtime != nil {
		l = m.Creationtime.Size()
		n += 1 + l + sovAri(uint64(l))
	}
	if m.Dialplan != nil {
		l = m.Dialplan.Size()
		n += 1 + l + sovAri(uint64(l))
	}
	l = len(m.Language)
	if l > 0 {
		n += 1 + l + sovAri(uint64(l))
	}
	if len(m.ChannelVars) > 0 {
		for k, v := range m.ChannelVars {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovAri(uint64(len(k))) + 1 + len(v) + sovAri(uint64(len(v)))
			n += mapEntrySize + 1 + sovAri(uint64(mapEntrySize))
		}
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *DialplanCEP) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Context)
	if l > 0 {
		n += 1 + l + sovAri(uint64(l))
	}
	l = len(m.Exten)
	if l > 0 {
		n += 1 + l + sovAri(uint64(l))
	}
	if m.Priority != 0 {
		n += 1 + sovAri(uint64(m.Priority))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovAri(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAri(x uint64) (n int) {
	return sovAri(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Key) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAri
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Key: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Key: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kind", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAri
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAri
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAri
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Kind = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAri
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAri
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAri
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Node", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAri
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAri
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAri
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Node = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dialog", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAri
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAri
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAri
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Dialog = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field App", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAri
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAri
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAri
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.App = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAri(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAri
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *CallerID) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAri
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CallerID: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CallerID: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAri
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAri
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAri
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Number", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAri
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAri
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAri
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Number = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAri(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAri
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ChannelData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAri
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ChannelData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ChannelData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Key", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAri
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAri
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAri
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Key == nil {
				m.Key = &Key{}
			}
			if err := m.Key.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAri
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAri
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAri
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAri
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAri
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAri
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field State", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAri
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAri
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAri
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.State = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Accountcode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAri
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAri
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAri
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Accountcode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Caller", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAri
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAri
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAri
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Caller == nil {
				m.Caller = &CallerID{}
			}
			if err := m.Caller.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Connected", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAri
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAri
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAri
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Connected == nil {
				m.Connected = &CallerID{}
			}
			if err := m.Connected.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creationtime", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAri
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAri
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAri
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Creationtime == nil {
				m.Creationtime = &types.Timestamp{}
			}
			if err := m.Creationtime.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Dialplan", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAri
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAri
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAri
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Dialplan == nil {
				m.Dialplan = &DialplanCEP{}
			}
			if err := m.Dialplan.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Language", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAri
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAri
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAri
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Language = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChannelVars", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAri
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAri
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAri
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.ChannelVars == nil {
				m.ChannelVars = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowAri
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowAri
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthAri
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthAri
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowAri
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthAri
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthAri
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipAri(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthAri
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.ChannelVars[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAri(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAri
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DialplanCEP) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAri
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DialplanCEP: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DialplanCEP: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Context", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAri
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAri
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAri
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Context = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Exten", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAri
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAri
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAri
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Exten = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Priority", wireType)
			}
			m.Priority = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAri
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Priority |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipAri(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAri
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAri(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAri
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAri
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAri
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAri
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAri
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAri
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAri        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAri          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAri = fmt.Errorf("proto: unexpected end of group")
)
