package arimocks

import mock "github.com/stretchr/testify/mock"

// BridgeEvent is an autogenerated mock type for the BridgeEvent type
type BridgeEvent struct {
	mock.Mock
}

// GetBridgeIDs provides a mock function with given fields:
func (_m *BridgeEvent) GetBridgeIDs() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}
