package arimocks

import ari "github.com/CyCoreSystems/ari"
import mock "github.com/stretchr/testify/mock"

// Config is an autogenerated mock type for the Config type
type Config struct {
	mock.Mock
}

// Data provides a mock function with given fields: configClass, objectType, key
func (_m *Config) Data(configClass *ari.Key, objectType *ari.Key, key *ari.Key) (*ari.ConfigData, error) {
	ret := _m.Called(configClass, objectType, key)

	var r0 *ari.ConfigData
	if rf, ok := ret.Get(0).(func(*ari.Key, *ari.Key, *ari.Key) *ari.ConfigData); ok {
		r0 = rf(configClass, objectType, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ari.ConfigData)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*ari.Key, *ari.Key, *ari.Key) error); ok {
		r1 = rf(configClass, objectType, key)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: configClass, objectType, key
func (_m *Config) Delete(configClass *ari.Key, objectType *ari.Key, key *ari.Key) error {
	ret := _m.Called(configClass, objectType, key)

	var r0 error
	if rf, ok := ret.Get(0).(func(*ari.Key, *ari.Key, *ari.Key) error); ok {
		r0 = rf(configClass, objectType, key)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Get provides a mock function with given fields: configClass, objectType, key
func (_m *Config) Get(configClass *ari.Key, objectType *ari.Key, key *ari.Key) ari.ConfigHandle {
	ret := _m.Called(configClass, objectType, key)

	var r0 ari.ConfigHandle
	if rf, ok := ret.Get(0).(func(*ari.Key, *ari.Key, *ari.Key) ari.ConfigHandle); ok {
		r0 = rf(configClass, objectType, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ari.ConfigHandle)
		}
	}

	return r0
}

// Update provides a mock function with given fields: configClass, objectType, key, tuples
func (_m *Config) Update(configClass *ari.Key, objectType *ari.Key, key *ari.Key, tuples []ari.ConfigTuple) error {
	ret := _m.Called(configClass, objectType, key, tuples)

	var r0 error
	if rf, ok := ret.Get(0).(func(*ari.Key, *ari.Key, *ari.Key, []ari.ConfigTuple) error); ok {
		r0 = rf(configClass, objectType, key, tuples)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
