// Code generated by mockery v2.16.0. DO NOT EDIT.

package arimocks

import (
	ari "github.com/Amtelco-Software/ari/v6"
	mock "github.com/stretchr/testify/mock"
)

// DTMFSender is an autogenerated mock type for the DTMFSender type
type DTMFSender struct {
	mock.Mock
}

// SendDTMF provides a mock function with given fields: dtmf, opts
func (_m *DTMFSender) SendDTMF(dtmf string, opts *ari.DTMFOptions) {
	_m.Called(dtmf, opts)
}

type mockConstructorTestingTNewDTMFSender interface {
	mock.TestingT
	Cleanup(func())
}

// NewDTMFSender creates a new instance of DTMFSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDTMFSender(t mockConstructorTestingTNewDTMFSender) *DTMFSender {
	mock := &DTMFSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
