// Code generated by mockery v2.16.0. DO NOT EDIT.

package arimocks

import (
	ari "github.com/Amtelco-Software/ari/v6"
	mock "github.com/stretchr/testify/mock"
)

// MatchFunc is an autogenerated mock type for the MatchFunc type
type MatchFunc struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0
func (_m *MatchFunc) Execute(_a0 *ari.Key) bool {
	ret := _m.Called(_a0)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*ari.Key) bool); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

type mockConstructorTestingTNewMatchFunc interface {
	mock.TestingT
	Cleanup(func())
}

// NewMatchFunc creates a new instance of MatchFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewMatchFunc(t mockConstructorTestingTNewMatchFunc) *MatchFunc {
	mock := &MatchFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
