package arimocks

import mock "github.com/stretchr/testify/mock"

// Variables is an autogenerated mock type for the Variables type
type Variables struct {
	mock.Mock
}

// Get provides a mock function with given fields: variable
func (_m *Variables) Get(variable string) (string, error) {
	ret := _m.Called(variable)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(variable)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(variable)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: variable, value
func (_m *Variables) Set(variable string, value string) error {
	ret := _m.Called(variable, value)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(variable, value)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
