package main

var templateFile = `
// file generated by eventgen

package ari

// EventTypes enumerates the list of event types
type EventTypes struct {
	All string
	{{range .}}{{.Name}} string
	{{end}}
}

// Events is the instance for grabbing event types
var Events EventTypes

func init() {
	Events.All = "all"
	{{range .}} Events.{{.Name}} = "{{.Event}}"
	{{end}}
}

// Parse parses the message into the specific eventer
func (ev *EventTypes) Parse(msg *Message) Event {
	var e Event
	switch msg.Type {
	{{range .}}case ev.{{.Name}}:
		e = &{{.Name}}{}
	{{end}}
	default:
		e = &EventData{}
	}
	err := msg.DecodeAs(e)
	if err != nil {
		return e
	}

	return e
}


{{range .}}
// {{.Name}} - "{{.Description}}"
type {{.Name}} struct {
	EventData
	{{range .Properties}}{{.Name}} {{.Type}} {{.Mapping}} {{.Description}}
	{{end}} }
{{end}}
`
