// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/CyCoreSystems/ari (interfaces: Variables)

package mock

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Variables interface
type MockVariables struct {
	ctrl     *gomock.Controller
	recorder *_MockVariablesRecorder
}

// Recorder for MockVariables (not exported)
type _MockVariablesRecorder struct {
	mock *MockVariables
}

func NewMockVariables(ctrl *gomock.Controller) *MockVariables {
	mock := &MockVariables{ctrl: ctrl}
	mock.recorder = &_MockVariablesRecorder{mock}
	return mock
}

func (_m *MockVariables) EXPECT() *_MockVariablesRecorder {
	return _m.recorder
}

func (_m *MockVariables) Get(_param0 string) (string, error) {
	ret := _m.ctrl.Call(_m, "Get", _param0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockVariablesRecorder) Get(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Get", arg0)
}

func (_m *MockVariables) Set(_param0 string, _param1 string) error {
	ret := _m.ctrl.Call(_m, "Set", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockVariablesRecorder) Set(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Set", arg0, arg1)
}
