// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pb/ari.proto

/*
Package pb is a generated protocol buffer package.

It is generated from these files:
	pb/ari.proto

It has these top-level messages:
	Key
*/
package pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Key identifies a unique resource in the system
type Key struct {
	// Kind indicates the type of resource the Key points to.  e.g., "channel",
	// "bridge", etc.
	Kind string `protobuf:"bytes,1,opt,name=kind" json:"kind,omitempty"`
	// ID indicates the unique identifier of the resource
	Id string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	// Node indicates the unique identifier of the Asterisk node on which the
	// resource exists or will be created
	Node string `protobuf:"bytes,3,opt,name=node" json:"node,omitempty"`
	// Dialog indicates a named scope of the resource, for receiving events
	Dialog string `protobuf:"bytes,4,opt,name=dialog" json:"dialog,omitempty"`
	// App indiciates the ARI application that this key is bound to.
	App string `protobuf:"bytes,5,opt,name=app" json:"app,omitempty"`
}

func (m *Key) Reset()                    { *m = Key{} }
func (m *Key) String() string            { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()               {}
func (*Key) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Key) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Key) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Key) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *Key) GetDialog() string {
	if m != nil {
		return m.Dialog
	}
	return ""
}

func (m *Key) GetApp() string {
	if m != nil {
		return m.App
	}
	return ""
}

func init() {
	proto.RegisterType((*Key)(nil), "asterisk.ari.Key")
}

func init() { proto.RegisterFile("pb/ari.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 140 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x29, 0x48, 0xd2, 0x4f,
	0x2c, 0xca, 0xd4, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x49, 0x2c, 0x2e, 0x49, 0x2d, 0xca,
	0x2c, 0xce, 0xd6, 0x4b, 0x2c, 0xca, 0x54, 0x4a, 0xe7, 0x62, 0xf6, 0x4e, 0xad, 0x14, 0x12, 0xe2,
	0x62, 0xc9, 0xce, 0xcc, 0x4b, 0x91, 0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85, 0xf8,
	0xb8, 0x98, 0x32, 0x53, 0x24, 0x98, 0xc0, 0x22, 0x4c, 0x99, 0x29, 0x20, 0x35, 0x79, 0xf9, 0x29,
	0xa9, 0x12, 0xcc, 0x10, 0x35, 0x20, 0xb6, 0x90, 0x18, 0x17, 0x5b, 0x4a, 0x66, 0x62, 0x4e, 0x7e,
	0xba, 0x04, 0x0b, 0x58, 0x14, 0xca, 0x13, 0x12, 0xe0, 0x62, 0x4e, 0x2c, 0x28, 0x90, 0x60, 0x05,
	0x0b, 0x82, 0x98, 0x4e, 0x2c, 0x51, 0x4c, 0x05, 0x49, 0x49, 0x6c, 0x60, 0x37, 0x18, 0x03, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x57, 0x16, 0x78, 0x94, 0x93, 0x00, 0x00, 0x00,
}
