name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.3

    - name: lint
      uses: golangci/golangci-lint-action@v6.5.0
      with:
        args: ./...

    - name: Build API
      run: go build -v ./ ./stdbus ./rid

    - name: Build Clients
      run: go build -v ./client/native ./client/arimocks

    - name: Build Extensions
      run: go build -v ./ext/...

    - name: Test
      run: go test -v ./...
